apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: my-first-k8-deployment
spec:
  selector:
     matchLabels:
       app:  k8-app
  replicas: 2
  template:
    metadata: 
      labels:
        app: k8-app
    spec: 
      containers:
         - name: k8-app
           image: rwigara/k8s-app:latets
           ports:
            - containerPort: 3000


