apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: default
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployment
  template:
    metadata:
      labels:
        app: k8s-deployment
    spec:
      containers: 
        - name: k8s-deployment
          image: rwigara/k8s-app:latest
          ports:
            - containerPort: 3000

