apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  namespace: default
spec:
    type: LoadBalancer
    selector:
      app: k8s-deployment
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000